
// Generated by Cadence Genus(TM) Synthesis Solution 16.13-s036_1
// Generated on: Mar 16 2024 06:08:16 +06 (Mar 16 2024 00:08:16 UTC)

// Verification Directory fv/full_adder 

module full_adder(sum, cout, a, b, clk, rst);
  input [3:0] a, b;
  input clk, rst;
  output [3:0] sum;
  output cout;
  wire [3:0] a, b;
  wire clk, rst;
  wire [3:0] sum;
  wire cout;
  wire [3:0] A;
  wire [3:0] B;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  SDFFQX1HVT cout_reg(.CK (clk), .D (cout), .SI (n_14), .SE (rst), .Q
       (cout));
  SDFFQX1HVT \sum_reg[3] (.CK (clk), .D (sum[3]), .SI (n_15), .SE
       (rst), .Q (sum[3]));
  ADDFX1HVT g155(.A (A[3]), .B (B[3]), .CI (n_12), .CO (n_14), .S
       (n_15));
  SDFFQX1HVT \sum_reg[2] (.CK (clk), .D (sum[2]), .SI (n_13), .SE
       (rst), .Q (sum[2]));
  ADDFX1HVT g157(.A (A[2]), .B (B[2]), .CI (n_10), .CO (n_12), .S
       (n_13));
  SDFFQX1HVT \sum_reg[1] (.CK (clk), .D (sum[1]), .SI (n_11), .SE
       (rst), .Q (sum[1]));
  ADDFX1HVT g159(.A (A[1]), .B (B[1]), .CI (n_8), .CO (n_10), .S
       (n_11));
  SDFFQX1HVT \sum_reg[0] (.CK (clk), .D (sum[0]), .SI (n_9), .SE (rst),
       .Q (sum[0]));
  ADDHX1HVT g161(.A (B[0]), .B (A[0]), .CO (n_8), .S (n_9));
  DFFQXLHVT \B_reg[1] (.CK (clk), .D (n_2), .Q (B[1]));
  DFFHQX1HVT \A_reg[3] (.CK (clk), .D (n_4), .Q (A[3]));
  DFFQXLHVT \A_reg[2] (.CK (clk), .D (n_6), .Q (A[2]));
  DFFQXLHVT \B_reg[2] (.CK (clk), .D (n_1), .Q (B[2]));
  DFFHQX1HVT \B_reg[3] (.CK (clk), .D (n_0), .Q (B[3]));
  DFFQXLHVT \A_reg[0] (.CK (clk), .D (n_5), .Q (A[0]));
  DFFQXLHVT \B_reg[0] (.CK (clk), .D (n_3), .Q (B[0]));
  DFFQXLHVT \A_reg[1] (.CK (clk), .D (n_7), .Q (A[1]));
  AND2XLHVT g172(.A (rst), .B (a[1]), .Y (n_7));
  AND2XLHVT g171(.A (rst), .B (a[2]), .Y (n_6));
  AND2XLHVT g170(.A (rst), .B (a[0]), .Y (n_5));
  AND2XLHVT g173(.A (rst), .B (a[3]), .Y (n_4));
  AND2XLHVT g176(.A (rst), .B (b[0]), .Y (n_3));
  AND2XLHVT g175(.A (rst), .B (b[1]), .Y (n_2));
  AND2XLHVT g174(.A (rst), .B (b[2]), .Y (n_1));
  AND2XLHVT g177(.A (rst), .B (b[3]), .Y (n_0));
endmodule

